---
- hosts: all
  become: True
  tasks:
  - name: Update packages list
    apt: update_cache=yes

  - name: Install Desktop GUI Environment (XFCE4)
    apt:
      name: xfce4
      state: present

  - name: Install RDP Server
    apt:
      name: xrdp
      state: present

  - name: Enable XFCE4 as Desktop Env in xrdp config
    - lineinfile:
      path: /etc/xrdp/startwm.sh
      regexp: '^startxfce4'
      line: 'startxfce4'

  - name: Allow RDP port 3389 in firewall/UFW settings
    ufw:
      rule: allow
      port: 3389
      proto: tcp